service: s3-file-upload
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  memorySize: 128
functions:
  app:
    handler: app/app.handler
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
  uploadImage:
    handler: app/app.handler
    events:
      - http: 'POST /upload'

plugins:
 - serverless-apigw-binary
custom:
  apigwBinary:
    types:           #list of mime-types
      - 'image/jpeg'
      - 'image/jpg'
      - 'image/png'
      - 'image/gif'
      - 'text/html'